# Generated by Django 4.2.4 on 2023-08-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=255, unique=True)),
                ('engine_id', models.CharField(max_length=255)),
                ('transmission_id', models.CharField(max_length=255)),
                ('drive_axle_id', models.CharField(max_length=255)),
                ('steering_axle_id', models.CharField(max_length=255)),
                ('supply_contract_data', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=255)),
                ('consignee_address', models.CharField(max_length=255)),
                ('car_config', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'complaint_types',
            },
        ),
        migrations.CreateModel(
            name='DriveAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rear_axle_models',
            },
        ),
        migrations.CreateModel(
            name='EngineModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'engine_models',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maintenance_types',
            },
        ),
        migrations.CreateModel(
            name='RestorationMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'restoration_methods',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_axle_models',
            },
        ),
        migrations.CreateModel(
            name='Technics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'technics',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transmission_models',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_failure', models.DateField()),
                ('operating_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('failure_description', models.TextField()),
                ('used_spare_parts', models.TextField()),
                ('restoration_date', models.DateField()),
                ('downtime_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.car')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.complainttype')),
                ('restoration_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.restorationmethods')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany')),
            ],
            options={
                'ordering': ['date_of_failure'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order_number', models.CharField(max_length=255)),
                ('work_order_date', models.DateField()),
                ('service_organization', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.car')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.maintenancetype')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany')),
            ],
            options={
                'ordering': ['maintenance_date'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='drive_axle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.driveaxletype'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.enginemodels'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.technics'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.servicecompany'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering_axle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.steeringaxletype'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_management.transmissionmodels'),
        ),
    ]
